############################################################################
# apps/examples/my_client_raw/Makefile
############################################################################

include $(APPDIR)/Make.defs

# Nombre del programa
PROGNAME = my_client_raw
PRIORITY = SCHED_PRIORITY_DEFAULT

STACKSIZE = $(CONFIG_EXAMPLES_MY_CLIENT_RAW_STACKSIZE)

# Archivo C principal
MAINSRC = my_client_raw_main.c

MODULE = $(CONFIG_EXAMPLES_MY_CLIENT_RAW)

include $(APPDIR)/Application.mk

